var images = [
	"img/avatar.jpg",
	"img/dogapp.jpg",
	"img/hobby.jpg",
	"img/photo.jpg",
	"img/school.jpg",
	"img/tyj.jpg",
	"img/weixin.jpg",
	"img/xgb.jpg",
	"img/xinlang.jpg",
	"img/yundong.jpg",
	"img/yunyue.jpg"
];
$(function(){
	var lsitenManager = new lsiten();
	lsitenManager.addPage("home")
					 .addComponent("avartar",{
						 type:"base",
						 text: "",
						 center:true,
						 width:100,
						 height:100,
						 animateOption:{
							duration:2000
						 },
						 css:{
							 textAlign:"center",
							 backgroundColor:"#ccc",
							 top:50,
							 lineHeight:"100px",
							 borderRadius:"50%",
							 border:"2px #999 solid",
							 opacity:0
						 },
						 bg:"img/avatar.jpg",
						 animateIn:{opacity:1},
						 animateOut:{opacity:0}
					 })
					.addComponent("name",{
						type:"base",
						text: "雷诗城 (Eric)",
						center:true,
						width:200,
						height:30,
						startTime:100,
						css:{
							textAlign:"center",
							top:210,
							color:"#fff",
							fontSize:"18px",
							fontWeight:"bold",
							lineHeight:"30px",
							borderBottom:"1px rgb(163, 190, 183) dashed",
							opacity:0
						},
						animateIn:{opacity:1,top:180},
						animateOut:{opacity:0,top:210}
					})
					.addComponent("phone",{
						type:"base",
						text: "",
						html:"电话：18565884671<span style='margin-left:20px'>邮箱：1304906404@qq.com</span>",
						center:true,
						width:430,
						height:30,
						startTime:200,
						css:{
							textAlign:"center",
							top:260,
							color:"#fff",
							fontSize:"16px",
							lineHeight:"30px",
							borderBottom:"1px rgb(163, 190, 183) dashed",
							opacity:0
						},
						animateIn:{opacity:1,top:230},
						animateOut:{opacity:0,top:260}
					})
					.addComponent("github",{
						type:"base",
						text: "",
						html:githubHtml,
						center:true,
						width:300,
						height:60,
						startTime:300,
						css:{
							textAlign:"center",
							top:290,
							color:"#fff",
							fontSize:"16px",
							lineHeight:"25px",
							borderBottom:"1px rgb(163, 190, 183) dashed",
							opacity:0
						},
						animateIn:{opacity:1,top:260},
						animateOut:{opacity:0,top:290}
					})
					.addComponent("signature",{
						type:"base",
						text: "",
						html:signatureHtml,
						center:true,
						width:600,
						height:60,
						startTime:400,
						css:{
							textAlign:"center",
							top:340,
							color:"#fff",
							fontSize:"14px",
							lineHeight:"25px",
							opacity:0
						},
						animateIn:{opacity:1},
						animateOut:{opacity:0}
					})
					.addComponent("hobby",{
						type:"hobby",
						center:true,
						width:200,
						height:200,
						startTime:600,
						data:[
							{
								title:"旅游",
								des:'长城雄伟霸气，大理风华雪月，丽江千姿百态，一起去看世界吧👍',
								content:"我喜欢旅游，因为人生就像一场旅行，旅游可以放松身心，开阔眼界，洗涤心境，大理风花雪月，丽江千姿百态，泸沽湖与世隔绝，让我心向往之...",
								bg:"img/hobby.jpg",
								bgcolor:"#AA1700",
							},
							{
								title:"摄影",
								des:'摄影是一个艺术，她能让你女朋友看起来像女神，也可以像女神经...',
								content:"摄影一词是源于希腊语φῶς phos（光线）和 γραφι graphis（绘画、绘图）。摄影让我感觉像是个画家一样去谱写我的人生，记录下我开心的每一刻。",
								bg:"img/photo.jpg",
								bgcolor:"#4AA113",
								left: "-120%"
							},
							{
								title:"运动",
								des:'人生在于折腾，当然这也包括运动，😂',
								content:"我喜欢各类球类运动，例如篮球，乒乓球，羽毛球等，当然篮球是凭借身高优势的，哈哈哈，乒乓球，羽毛球的技术都不差哟。",
								bg:"img/yundong.jpg",
								bgcolor:"#FF8A00",
								left: "120%"
							},
							{
								title:"音乐",
								des:'音乐是个陶冶情操的玩意儿,工作累了吹吹口琴，弹弹吉他...',
								content:"我一直很羡慕那些一不开心就随时来一首卡农的人，因为我不会😂😂，我一直梦想像爱因斯坦那样用小提琴来激发自己的创意，当然我不会小提琴😂",
								bg:"img/yunyue.jpg",
								bgcolor:"#20CB8C",
								left: "-240%"
							},
							{
								title:"学习",
								des:'终身学习是我的的原则😂',
								content:"我是个喜欢自学的人，在慕课网学习时长达588小时44分，技术胖网站所有vue相关资料，各种文档如thinkphp，ionic等，曾经为了学ionic各种学英文😂",
								bg:"img/xuexi.jpg",
								bgcolor:"#FFAB41",
								left: "240%"
							}
						],
						css:{
							textAlign:"center",
							top:510,
							color:"#fff"
						}
					})
				 .addPage("skill")
					 .addComponent("point",{
						type:"point",
						center:true,
						width:200,
						height:200,
						data:[
							["我的技能",1,'green'],
							["PHP",.8,'#6073AF',"-100%",'-100%'],
							["JavaScript",.4,'#2E65AD',"160%","-20%"],
							["Jquery",.6,'#182533',"120%","-120%"],
							["Vue",.7,'#39AF78',"-120%","120%"],
							["Mysql",.5,'#094468',"120%","50%"],
							["Linux",.3,'#2D2D2D',"-60%","40%"],
							["World",.6,'#285DA0',"20%","120%"],
							["Excel",.5,'#1D6239',"150%","120%"],
							["PPT",.6,'#CC3D22',"-180%","20%"],
							["Photoshop",.4,'#0F1839',"20%","-60%"],
						],
						css:{
							textAlign:"center",
							top:"50%",
							marginTop:"-100px"				
						}
					 })
				 .addPage("project")
					.addComponent("tips",{
						type:"base",
						text: "",
						html:tips,
						center:true,
						width:800,
						height:100,
						css:{
							textAlign:"center",
							top:0,
							opacity:0					
						},
						animateIn:{opacity:1,top:120},
						animateOut:{opacity:0,top:0}
					})
					.addComponent("projectTitle",{
						type:"base",
						text: "重点项目",
						center:true,
						width:100,
						height:40,
						css:{
							textAlign:"center",
							bottom:490,
							color:"#666",
							fontSize:"25px",
							fontWeight:"bold",
							lineHeight:"40px",
							opacity:0
						},
						animateIn:{opacity:1,bottom:460},
						animateOut:{opacity:0,bottom:490}
					})
					.addComponent("impotantProject",{
						type:"base",
						text: "",
						html:impotantProjects,
						center:true,
						width:900,
						height:330,
						css:{
							textAlign:"center",
							bottom:0,
							opacity:0				
						},
						animateIn:{opacity:1,bottom:70},
						animateOut:{opacity:0,bottom:0}
					})
				 .addPage("job")
					.addComponent("jobTitle",{
						type:"base",
						text: "简单的工作经历",
						center:true,
						width:300,
						height:40,
						css:{
							textAlign:"center",
							fontSize:"40px",
							fontWeight:"bold",
							color:"#666",
							top:190,
							lineHeight:"40px",
							opacity:0					
						},
						animateIn:{opacity:1,top:150},
						animateOut:{opacity:0,top:190}
					})
					.addComponent("job",{
						type:"timelist",
						data: [
							{
								title:"2013年:",
								content:"网络部（e缘网站负责设备维护）",
								startTime:500
							},
							{
								title:"2014年-2016年:",
								content:"技术部部长（e缘网站站点维护，服务器维护）",
								startTime:600
							},
							{
								title:"2016年-2017年:",
								content:"富士康idpbg移动端开发（前端开发，页面维护）",
								startTime:700
							}
						],
						center:true,
						width:600,
						height:300,
						css:{
							textAlign:"center",
							top:260,
						}
					})
				 .addPage("contact")
					.addComponent("contact",{
						type:"base",
						html: contactTitle,
						width:"100%",
						height:60,
						css:{
							textAlign:"left",
							backgroundColor:"rgba(0,0,0,.5)",
							top:0,
							color:"#fff",
							lineHeight:"60px",
							borderLeft:"5px solid #000",
							width:0,
							opacity:0				
						},
						animateIn:{opacity:1,width:"100%"},
						animateOut:{opacity:0,width:0}
					})
					.addComponent("callme",{
						type:"base",
						html: callMe,
						center:true,
						height:30,
						width:400,
						startTime:500,
						css:{
							textAlign:"left",
							top:180,
							color:"#fff",
							fontSize:"18px",
							lineHeight:"30px",
							opacity:0,
							width:0
						},
						animateIn:{opacity:1,width:400},
						animateOut:{opacity:0,width:0}
					})
					.addComponent("emailme",{
						type:"base",
						html: emailme,
						center:true,
						height:30,
						width:400,
						startTime:700,
						css:{
							textAlign:"left",
							top:240,
							color:"#fff",
							fontSize:"18px",
							lineHeight:"30px",
							opacity:0,
							width:0
						},
						animateIn:{opacity:1,width:400},
						animateOut:{opacity:0,width:0}
					})
					.addComponent("qq",{
						type:"base",
						html: myqq,
						center:true,
						height:30,
						width:400,
						startTime:900,
						css:{
							textAlign:"left",
							top:290,
							color:"#fff",
							fontSize:"18px",
							lineHeight:"30px",
							opacity:0,
							width:0
						},
						animateIn:{opacity:1,width:400},
						animateOut:{opacity:0,width:0}
					})
					.addComponent("weixin",{
						type:"base",
						center:true,
						height:150,
						width:150,
						startTime:900,
						bg:"img/weixin.jpg",
						css:{
							textAlign:"left",
							top:290,
							color:"#fff",
							fontSize:"18px",
							lineHeight:"30px",
							opacity:0,
							border:"1px solid #999",
							borderRadius:"6px"
						},
						animateIn:{opacity:1,top:360,marginLeft:"-200px"},
						animateOut:{opacity:0,top:290,marginLeft:"-75px"}
					})
					.addComponent("weibo",{
						type:"base",
						center:true,
						height:150,
						width:150,
						startTime:900,
						bg:"img/xinlang.jpg",
						css:{
							textAlign:"left",
							top:290,
							color:"#fff",
							fontSize:"18px",
							lineHeight:"30px",
							opacity:0,
							border:"1px solid #999",
							borderRadius:"6px"
						},
						animateIn:{opacity:1,top:360,marginLeft:"20px"},
						animateOut:{opacity:0,top:290,marginLeft:"-75px"}
					})
				 .loaderHandler(images);
})